/**
 * Constantes de Países do Mundo
 * Lista de países com código ISO, código de telefone e moeda
 */

export const COUNTRIES = [
  { name: 'Afeganistão', code: 'AF', phoneCode: '+93', currency: 'AFN' },
  { name: 'Albânia', code: 'AL', phoneCode: '+355', currency: 'ALL' },
  { name: 'Argélia', code: 'DZ', phoneCode: '+213', currency: 'DZD' },
  { name: 'Andorra', code: 'AD', phoneCode: '+376', currency: 'EUR' },
  { name: 'Angola', code: 'AO', phoneCode: '+244', currency: 'AOA' },
  { name: 'Anguila', code: 'AI', phoneCode: '+1-264', currency: 'XCD' },
  { name: 'Antártida', code: 'AQ', phoneCode: '+672', currency: 'AUD' },
  { name: 'Antígua e Barbuda', code: 'AG', phoneCode: '+1-268', currency: 'XCD' },
  { name: 'Arábia Saudita', code: 'SA', phoneCode: '+966', currency: 'SAR' },
  { name: 'Argélia', code: 'DZ', phoneCode: '+213', currency: 'DZD' },
  { name: 'Argentina', code: 'AR', phoneCode: '+54', currency: 'ARS' },
  { name: 'Armênia', code: 'AM', phoneCode: '+374', currency: 'AMD' },
  { name: 'Aruba', code: 'AW', phoneCode: '+297', currency: 'AWG' },
  { name: 'Austrália', code: 'AU', phoneCode: '+61', currency: 'AUD' },
  { name: 'Áustria', code: 'AT', phoneCode: '+43', currency: 'EUR' },
  { name: 'Azerbaijão', code: 'AZ', phoneCode: '+994', currency: 'AZN' },
  { name: 'Bahamas', code: 'BS', phoneCode: '+1-242', currency: 'BSD' },
  { name: 'Bahrein', code: 'BH', phoneCode: '+973', currency: 'BHD' },
  { name: 'Bangladesh', code: 'BD', phoneCode: '+880', currency: 'BDT' },
  { name: 'Barbados', code: 'BB', phoneCode: '+1-246', currency: 'BBD' },
  { name: 'Bélgica', code: 'BE', phoneCode: '+32', currency: 'EUR' },
  { name: 'Belize', code: 'BZ', phoneCode: '+501', currency: 'BZD' },
  { name: 'Benin', code: 'BJ', phoneCode: '+229', currency: 'XOF' },
  { name: 'Bermudas', code: 'BM', phoneCode: '+1-441', currency: 'BMD' },
  { name: 'Bielorrússia', code: 'BY', phoneCode: '+375', currency: 'BYN' },
  { name: 'Birmânia', code: 'MM', phoneCode: '+95', currency: 'MMK' },
  { name: 'Bolívia', code: 'BO', phoneCode: '+591', currency: 'BOB' },
  { name: 'Bósnia e Herzegovina', code: 'BA', phoneCode: '+387', currency: 'BAM' },
  { name: 'Botsuana', code: 'BW', phoneCode: '+267', currency: 'BWP' },
  { name: 'Brasil', code: 'BR', phoneCode: '+55', currency: 'BRL' },
  { name: 'Brunei', code: 'BN', phoneCode: '+673', currency: 'BND' },
  { name: 'Bulgária', code: 'BG', phoneCode: '+359', currency: 'BGN' },
  { name: 'Burkina Faso', code: 'BF', phoneCode: '+226', currency: 'XOF' },
  { name: 'Burundi', code: 'BI', phoneCode: '+257', currency: 'BIF' },
  { name: 'Butão', code: 'BT', phoneCode: '+975', currency: 'BTN' },
  { name: 'Cabo Verde', code: 'CV', phoneCode: '+238', currency: 'CVE' },
  { name: 'Camarões', code: 'CM', phoneCode: '+237', currency: 'XAF' },
  { name: 'Camboja', code: 'KH', phoneCode: '+855', currency: 'KHR' },
  { name: 'Canadá', code: 'CA', phoneCode: '+1', currency: 'CAD' },
  { name: 'Catar', code: 'QA', phoneCode: '+974', currency: 'QAR' },
  { name: 'Cazaquistão', code: 'KZ', phoneCode: '+7', currency: 'KZT' },
  { name: 'Chade', code: 'TD', phoneCode: '+235', currency: 'XAF' },
  { name: 'Chile', code: 'CL', phoneCode: '+56', currency: 'CLP' },
  { name: 'China', code: 'CN', phoneCode: '+86', currency: 'CNY' },
  { name: 'Chipre', code: 'CY', phoneCode: '+357', currency: 'EUR' },
  { name: 'Colômbia', code: 'CO', phoneCode: '+57', currency: 'COP' },
  { name: 'Comores', code: 'KM', phoneCode: '+269', currency: 'KMF' },
  { name: 'Congo', code: 'CG', phoneCode: '+242', currency: 'XAF' },
  { name: 'Coreia do Norte', code: 'KP', phoneCode: '+850', currency: 'KPW' },
  { name: 'Coreia do Sul', code: 'KR', phoneCode: '+82', currency: 'KRW' },
  { name: 'Costa do Marfim', code: 'CI', phoneCode: '+225', currency: 'XOF' },
  { name: 'Costa Rica', code: 'CR', phoneCode: '+506', currency: 'CRC' },
  { name: 'Croácia', code: 'HR', phoneCode: '+385', currency: 'EUR' },
  { name: 'Cuba', code: 'CU', phoneCode: '+53', currency: 'CUP' },
  { name: 'Curaçao', code: 'CW', phoneCode: '+599', currency: 'ANG' },
  { name: 'Dinamarca', code: 'DK', phoneCode: '+45', currency: 'DKK' },
  { name: 'Djibuti', code: 'DJ', phoneCode: '+253', currency: 'DJF' },
  { name: 'Dominica', code: 'DM', phoneCode: '+1-767', currency: 'XCD' },
  { name: 'Egito', code: 'EG', phoneCode: '+20', currency: 'EGP' },
  { name: 'Emirados Árabes Unidos', code: 'AE', phoneCode: '+971', currency: 'AED' },
  { name: 'Equador', code: 'EC', phoneCode: '+593', currency: 'USD' },
  { name: 'Eritreia', code: 'ER', phoneCode: '+291', currency: 'ERN' },
  { name: 'Eslováquia', code: 'SK', phoneCode: '+421', currency: 'EUR' },
  { name: 'Eslovênia', code: 'SI', phoneCode: '+386', currency: 'EUR' },
  { name: 'Espanha', code: 'ES', phoneCode: '+34', currency: 'EUR' },
  { name: 'Estados Unidos', code: 'US', phoneCode: '+1', currency: 'USD' },
  { name: 'Estônia', code: 'EE', phoneCode: '+372', currency: 'EUR' },
  { name: 'Etiópia', code: 'ET', phoneCode: '+251', currency: 'ETB' },
  { name: 'Fiji', code: 'FJ', phoneCode: '+679', currency: 'FJD' },
  { name: 'Filipinas', code: 'PH', phoneCode: '+63', currency: 'PHP' },
  { name: 'Finlândia', code: 'FI', phoneCode: '+358', currency: 'EUR' },
  { name: 'França', code: 'FR', phoneCode: '+33', currency: 'EUR' },
  { name: 'Gabão', code: 'GA', phoneCode: '+241', currency: 'XAF' },
  { name: 'Gâmbia', code: 'GM', phoneCode: '+220', currency: 'GMD' },
  { name: 'Gana', code: 'GH', phoneCode: '+233', currency: 'GHS' },
  { name: 'Geórgia', code: 'GE', phoneCode: '+995', currency: 'GEL' },
  { name: 'Gibraltar', code: 'GI', phoneCode: '+350', currency: 'GIP' },
  { name: 'Grécia', code: 'GR', phoneCode: '+30', currency: 'EUR' },
  { name: 'Granada', code: 'GD', phoneCode: '+1-473', currency: 'XCD' },
  { name: 'Groenlândia', code: 'GL', phoneCode: '+299', currency: 'DKK' },
  { name: 'Guam', code: 'GU', phoneCode: '+1-671', currency: 'USD' },
  { name: 'Guatemala', code: 'GT', phoneCode: '+502', currency: 'GTQ' },
  { name: 'Guernsey', code: 'GG', phoneCode: '+44-1481', currency: 'GBP' },
  { name: 'Guiana', code: 'GY', phoneCode: '+592', currency: 'GYD' },
  { name: 'Guiana Francesa', code: 'GF', phoneCode: '+594', currency: 'EUR' },
  { name: 'Guiné', code: 'GN', phoneCode: '+224', currency: 'GNF' },
  { name: 'Guiné Equatorial', code: 'GQ', phoneCode: '+240', currency: 'XAF' },
  { name: 'Guiné-Bissau', code: 'GW', phoneCode: '+245', currency: 'XOF' },
  { name: 'Haiti', code: 'HT', phoneCode: '+509', currency: 'HTG' },
  { name: 'Honduras', code: 'HN', phoneCode: '+504', currency: 'HNL' },
  { name: 'Hong Kong', code: 'HK', phoneCode: '+852', currency: 'HKD' },
  { name: 'Hungria', code: 'HU', phoneCode: '+36', currency: 'HUF' },
  { name: 'Iêmen', code: 'YE', phoneCode: '+967', currency: 'YER' },
  { name: 'Ilha Bouvet', code: 'BV', phoneCode: '+47', currency: 'NOK' },
  { name: 'Ilha Christmas', code: 'CX', phoneCode: '+61', currency: 'AUD' },
  { name: 'Ilha de Man', code: 'IM', phoneCode: '+44-1624', currency: 'GBP' },
  { name: 'Ilhas Åland', code: 'AX', phoneCode: '+358', currency: 'EUR' },
  { name: 'Ilhas Cayman', code: 'KY', phoneCode: '+1-345', currency: 'KYD' },
  { name: 'Ilhas Cocos', code: 'CC', phoneCode: '+61', currency: 'AUD' },
  { name: 'Ilhas Cook', code: 'CK', phoneCode: '+682', currency: 'NZD' },
  { name: 'Ilhas Faroé', code: 'FO', phoneCode: '+298', currency: 'DKK' },
  { name: 'Ilhas Heard e McDonald', code: 'HM', phoneCode: '+61', currency: 'AUD' },
  { name: 'Ilhas Mariana do Norte', code: 'MP', phoneCode: '+1-670', currency: 'USD' },
  { name: 'Ilhas Pitcairn', code: 'PN', phoneCode: '+64', currency: 'NZD' },
  { name: 'Ilhas Salomão', code: 'SB', phoneCode: '+677', currency: 'SBD' },
  { name: 'Ilhas Turcas e Caicos', code: 'TC', phoneCode: '+1-649', currency: 'USD' },
  { name: 'Ilhas Virgens Britânicas', code: 'VG', phoneCode: '+1-284', currency: 'USD' },
  { name: 'Ilhas Virgens Americanas', code: 'VI', phoneCode: '+1-340', currency: 'USD' },
  { name: 'Índia', code: 'IN', phoneCode: '+91', currency: 'INR' },
  { name: 'Indonésia', code: 'ID', phoneCode: '+62', currency: 'IDR' },
  { name: 'Irã', code: 'IR', phoneCode: '+98', currency: 'IRR' },
  { name: 'Iraque', code: 'IQ', phoneCode: '+964', currency: 'IQD' },
  { name: 'Irlanda', code: 'IE', phoneCode: '+353', currency: 'EUR' },
  { name: 'Islândia', code: 'IS', phoneCode: '+354', currency: 'ISK' },
  { name: 'Israel', code: 'IL', phoneCode: '+972', currency: 'ILS' },
  { name: 'Itália', code: 'IT', phoneCode: '+39', currency: 'EUR' },
  { name: 'Jamaica', code: 'JM', phoneCode: '+1-876', currency: 'JMD' },
  { name: 'Japão', code: 'JP', phoneCode: '+81', currency: 'JPY' },
  { name: 'Jersey', code: 'JE', phoneCode: '+44-1534', currency: 'GBP' },
  { name: 'Jordânia', code: 'JO', phoneCode: '+962', currency: 'JOD' },
  { name: 'Kiribati', code: 'KI', phoneCode: '+686', currency: 'AUD' },
  { name: 'Kosovo', code: 'XK', phoneCode: '+383', currency: 'EUR' },
  { name: 'Kuwait', code: 'KW', phoneCode: '+965', currency: 'KWD' },
  { name: 'Laos', code: 'LA', phoneCode: '+856', currency: 'LAK' },
  { name: 'Lesoto', code: 'LS', phoneCode: '+266', currency: 'LSL' },
  { name: 'Letônia', code: 'LV', phoneCode: '+371', currency: 'EUR' },
  { name: 'Líbano', code: 'LB', phoneCode: '+961', currency: 'LBP' },
  { name: 'Libéria', code: 'LR', phoneCode: '+231', currency: 'LRD' },
  { name: 'Líbia', code: 'LY', phoneCode: '+218', currency: 'LYD' },
  { name: 'Liechtenstein', code: 'LI', phoneCode: '+423', currency: 'CHF' },
  { name: 'Lituânia', code: 'LT', phoneCode: '+370', currency: 'EUR' },
  { name: 'Luxemburgo', code: 'LU', phoneCode: '+352', currency: 'EUR' },
  { name: 'Macau', code: 'MO', phoneCode: '+853', currency: 'MOP' },
  { name: 'Macedônia do Norte', code: 'MK', phoneCode: '+389', currency: 'MKD' },
  { name: 'Madagáscar', code: 'MG', phoneCode: '+261', currency: 'MGA' },
  { name: 'Malásia', code: 'MY', phoneCode: '+60', currency: 'MYR' },
  { name: 'Malaui', code: 'MW', phoneCode: '+265', currency: 'MWK' },
  { name: 'Maldivas', code: 'MV', phoneCode: '+960', currency: 'MVR' },
  { name: 'Mali', code: 'ML', phoneCode: '+223', currency: 'XOF' },
  { name: 'Malta', code: 'MT', phoneCode: '+356', currency: 'EUR' },
  { name: 'Marrocos', code: 'MA', phoneCode: '+212', currency: 'MAD' },
  { name: 'Martinica', code: 'MQ', phoneCode: '+596', currency: 'EUR' },
  { name: 'Maurício', code: 'MU', phoneCode: '+230', currency: 'MUR' },
  { name: 'Mauritânia', code: 'MR', phoneCode: '+222', currency: 'MRU' },
  { name: 'Mayotte', code: 'YT', phoneCode: '+262', currency: 'EUR' },
  { name: 'Médio Oriente', code: 'ME', phoneCode: '+382', currency: 'EUR' },
  { name: 'México', code: 'MX', phoneCode: '+52', currency: 'MXN' },
  { name: 'Micronésia', code: 'FM', phoneCode: '+691', currency: 'USD' },
  { name: 'Moçambique', code: 'MZ', phoneCode: '+258', currency: 'MZN' },
  { name: 'Moldávia', code: 'MD', phoneCode: '+373', currency: 'MDL' },
  { name: 'Mônaco', code: 'MC', phoneCode: '+377', currency: 'EUR' },
  { name: 'Mongólia', code: 'MN', phoneCode: '+976', currency: 'MNT' },
  { name: 'Montenegro', code: 'ME', phoneCode: '+382', currency: 'EUR' },
  { name: 'Montserrat', code: 'MS', phoneCode: '+1-664', currency: 'XCD' },
  { name: 'Namíbia', code: 'NA', phoneCode: '+264', currency: 'NAD' },
  { name: 'Nauru', code: 'NR', phoneCode: '+674', currency: 'AUD' },
  { name: 'Nepal', code: 'NP', phoneCode: '+977', currency: 'NPR' },
  { name: 'Nicarágua', code: 'NI', phoneCode: '+505', currency: 'NIO' },
  { name: 'Níger', code: 'NE', phoneCode: '+227', currency: 'XOF' },
  { name: 'Nigéria', code: 'NG', phoneCode: '+234', currency: 'NGN' },
  { name: 'Niue', code: 'NU', phoneCode: '+683', currency: 'NZD' },
  { name: 'Noruega', code: 'NO', phoneCode: '+47', currency: 'NOK' },
  { name: 'Nova Caledônia', code: 'NC', phoneCode: '+687', currency: 'XPF' },
  { name: 'Nova Zelândia', code: 'NZ', phoneCode: '+64', currency: 'NZD' },
  { name: 'Oman', code: 'OM', phoneCode: '+968', currency: 'OMR' },
  { name: 'Países Baixos', code: 'NL', phoneCode: '+31', currency: 'EUR' },
  { name: 'Palau', code: 'PW', phoneCode: '+680', currency: 'USD' },
  { name: 'Palestina', code: 'PS', phoneCode: '+970', currency: 'ILS' },
  { name: 'Panamá', code: 'PA', phoneCode: '+507', currency: 'PAB' },
  { name: 'Papua Nova Guiné', code: 'PG', phoneCode: '+675', currency: 'PGK' },
  { name: 'Paquistão', code: 'PK', phoneCode: '+92', currency: 'PKR' },
  { name: 'Paraguai', code: 'PY', phoneCode: '+595', currency: 'PYG' },
  { name: 'Peru', code: 'PE', phoneCode: '+51', currency: 'PEN' },
  { name: 'Polinésia Francesa', code: 'PF', phoneCode: '+689', currency: 'XPF' },
  { name: 'Polônia', code: 'PL', phoneCode: '+48', currency: 'PLN' },
  { name: 'Porto Rico', code: 'PR', phoneCode: '+1-787', currency: 'USD' },
  { name: 'Portugal', code: 'PT', phoneCode: '+351', currency: 'EUR' },
  { name: 'Reino Unido', code: 'GB', phoneCode: '+44', currency: 'GBP' },
  { name: 'República Centro-Africana', code: 'CF', phoneCode: '+236', currency: 'XAF' },
  { name: 'República Democrática do Congo', code: 'CD', phoneCode: '+243', currency: 'CDF' },
  { name: 'República Dominicana', code: 'DO', phoneCode: '+1-809', currency: 'DOP' },
  { name: 'República Tcheca', code: 'CZ', phoneCode: '+420', currency: 'CZK' },
  { name: 'Reunião', code: 'RE', phoneCode: '+262', currency: 'EUR' },
  { name: 'Romênia', code: 'RO', phoneCode: '+40', currency: 'RON' },
  { name: 'Ruanda', code: 'RW', phoneCode: '+250', currency: 'RWF' },
  { name: 'Rússia', code: 'RU', phoneCode: '+7', currency: 'RUB' },
  { name: 'Saara Ocidental', code: 'EH', phoneCode: '+212', currency: 'MAD' },
  { name: 'Saint Barthelemy', code: 'BL', phoneCode: '+590', currency: 'EUR' },
  { name: 'Saint Martin', code: 'MF', phoneCode: '+590', currency: 'EUR' },
  { name: 'Saint Pierre e Miquelon', code: 'PM', phoneCode: '+508', currency: 'EUR' },
  { name: 'Samoa', code: 'WS', phoneCode: '+685', currency: 'WST' },
  { name: 'Samoa Americana', code: 'AS', phoneCode: '+1-684', currency: 'USD' },
  { name: 'San Marino', code: 'SM', phoneCode: '+378', currency: 'EUR' },
  { name: 'Santa Helena', code: 'SH', phoneCode: '+290', currency: 'SHP' },
  { name: 'Santa Lúcia', code: 'LC', phoneCode: '+1-758', currency: 'XCD' },
  { name: 'Santo Antão e Granadinas', code: 'VC', phoneCode: '+1-784', currency: 'XCD' },
  { name: 'São Cristóvão e Névis', code: 'KN', phoneCode: '+1-869', currency: 'XCD' },
  { name: 'São Marino', code: 'SM', phoneCode: '+378', currency: 'EUR' },
  { name: 'São Tomé e Príncipe', code: 'ST', phoneCode: '+239', currency: 'STN' },
  { name: 'Seicheles', code: 'SC', phoneCode: '+248', currency: 'SCR' },
  { name: 'Senegal', code: 'SN', phoneCode: '+221', currency: 'XOF' },
  { name: 'Serra Leoa', code: 'SL', phoneCode: '+232', currency: 'SLL' },
  { name: 'Sérvia', code: 'RS', phoneCode: '+381', currency: 'RSD' },
  { name: 'Singapura', code: 'SG', phoneCode: '+65', currency: 'SGD' },
  { name: 'Sint Maarten', code: 'SX', phoneCode: '+1-721', currency: 'ANG' },
  { name: 'Síria', code: 'SY', phoneCode: '+963', currency: 'SYP' },
  { name: 'Somália', code: 'SO', phoneCode: '+252', currency: 'SOS' },
  { name: 'Sri Lanka', code: 'LK', phoneCode: '+94', currency: 'LKR' },
  { name: 'Suazilândia', code: 'SZ', phoneCode: '+268', currency: 'SZL' },
  { name: 'Sudão', code: 'SD', phoneCode: '+249', currency: 'SDG' },
  { name: 'Sudão do Sul', code: 'SS', phoneCode: '+211', currency: 'SSP' },
  { name: 'Suécia', code: 'SE', phoneCode: '+46', currency: 'SEK' },
  { name: 'Suíça', code: 'CH', phoneCode: '+41', currency: 'CHF' },
  { name: 'Suriname', code: 'SR', phoneCode: '+597', currency: 'SRD' },
  { name: 'Svalbard e Jan Mayen', code: 'SJ', phoneCode: '+47', currency: 'NOK' },
  { name: 'Tailândia', code: 'TH', phoneCode: '+66', currency: 'THB' },
  { name: 'Taiwan', code: 'TW', phoneCode: '+886', currency: 'TWD' },
  { name: 'Tajiquistão', code: 'TJ', phoneCode: '+992', currency: 'TJS' },
  { name: 'Tanzânia', code: 'TZ', phoneCode: '+255', currency: 'TZS' },
  { name: 'Território Britânico do Oceano Índico', code: 'IO', phoneCode: '+246', currency: 'USD' },
  { name: 'Timor-Leste', code: 'TL', phoneCode: '+670', currency: 'USD' },
  { name: 'Togo', code: 'TG', phoneCode: '+228', currency: 'XOF' },
  { name: 'Tokelau', code: 'TK', phoneCode: '+690', currency: 'NZD' },
  { name: 'Tonga', code: 'TO', phoneCode: '+676', currency: 'TOP' },
  { name: 'Trinidad e Tobago', code: 'TT', phoneCode: '+1-868', currency: 'TTD' },
  { name: 'Tunísia', code: 'TN', phoneCode: '+216', currency: 'TND' },
  { name: 'Turcomênia', code: 'TM', phoneCode: '+993', currency: 'TMT' },
  { name: 'Turquia', code: 'TR', phoneCode: '+90', currency: 'TRY' },
  { name: 'Tuvalu', code: 'TV', phoneCode: '+688', currency: 'AUD' },
  { name: 'Ucrânia', code: 'UA', phoneCode: '+380', currency: 'UAH' },
  { name: 'Uganda', code: 'UG', phoneCode: '+256', currency: 'UGX' },
  { name: 'Uruguai', code: 'UY', phoneCode: '+598', currency: 'UYU' },
  { name: 'Uzbequistão', code: 'UZ', phoneCode: '+998', currency: 'UZS' },
  { name: 'Vanuatu', code: 'VU', phoneCode: '+678', currency: 'VUV' },
  { name: 'Vaticano', code: 'VA', phoneCode: '+379', currency: 'EUR' },
  { name: 'Venezuela', code: 'VE', phoneCode: '+58', currency: 'VES' },
  { name: 'Vietnã', code: 'VN', phoneCode: '+84', currency: 'VND' },
  { name: 'Wallis e Futuna', code: 'WF', phoneCode: '+681', currency: 'XPF' },
  { name: 'Zâmbia', code: 'ZM', phoneCode: '+260', currency: 'ZMW' },
  { name: 'Zimbábue', code: 'ZW', phoneCode: '+263', currency: 'ZWL' },
];

export const COUNTRY_NAMES = COUNTRIES.map(c => c.name);
